#sample Makefile for using OpenGL in Linux
                                                                                
PROG	= ${fname:.cpp=}
all:	run
run:	$(PROG).cpp
	g++ $(PROG).cpp -lglut -lGL -lGLU && $(PROG)

